services:
  app-dev:
    restart: always
    container_name: gv-dev
    image: gv-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 3030:3000
